file_read = open('codingal.txt')
print("file is in read mode")
print(file_read.read())
file_read.close()
file_write = open('codingal.txt', 'w')
print("file is in write mode")
file_write.write("Hi I am penguin . I am 1 year old")
file_write.close()
file_append = open('codingal.txt', 'a')
print("file is in append mode")
file_append.write("Hi I am penguin . I am 1 year old")
file_append.close()